[build]
  publish = "dist"
  command = "rm -rf node_modules/.vite && pnpm run build"

[build.environment]
  NODE_VERSION = "22.16.0"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"